<!DOCTYPE html>
<html>
<head>
	<title>Main generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="description" content="Made with WOW Slider - Create beautiful, responsive image sliders in a few clicks. Awesome skins and animations. Slideshow html" />
	
	<!-- Start WOWSlider.com HEAD section --> <!-- add to the <head> of your page -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" />
	<script type="text/javascript" src="engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->

</head>
<body style="background-color:#d7d7d7;margin:auto">
	
	<!-- Start WOWSlider.com BODY section --> <!-- add to the <body> of your page -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
		<li><img src="data1/images/slide1.jpg" alt="slide1" title="slide1" id="wows1_0"/></li>
		<li><a href="http://wowslider.com"><img src="data1/images/slide31.jpg" alt="slider wordpress" title="slide31" id="wows1_1"/></a></li>
		<li><img src="data1/images/slide41.jpg" alt="slide41" title="slide41" id="wows1_2"/></li>
	</ul></div>
	<div class="ws_bullets"><div>
		<a href="#" title="slide1"><span><img src="data1/tooltips/slide1.jpg" alt="slide1"/>1</span></a>
		<a href="#" title="slide31"><span><img src="data1/tooltips/slide31.jpg" alt="slide31"/>2</span></a>
		<a href="#" title="slide41"><span><img src="data1/tooltips/slide41.jpg" alt="slide41"/>3</span></a>
	</div></div><div class="ws_script" style="position:absolute;left:-99%"><a href="http://wowslider.com">slideshow html</a> by WOWSlider.com v7.5</div>
	<div class="ws_shadow"></div>
	</div>	
	<script type="text/javascript" src="engine1/wowslider.js"></script>
	<script type="text/javascript" src="engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->

</body>
</html>